export const ROUTES = {
  root: '/',
  login: '/login',
  register: '/register',
  dashboard: '/dashboard',
  profile: '/profile',
  settings: '/settings',
  onboarding: '/onboarding',
  forceResetPassword: '/force-reset-password',
  adminCreators: '/admin/creators',
  adminReports: '/admin/reports',
  modules: '/modules',
  introduction: 'introduction',
  drafts: 'drafts',
  moduleId: ':moduleId',
  create: 'create',
  grammarRuleId: ':grammarRuleId',
  grammarRule: 'grammarRule',
  grammarRuleModuleId: ':grammarRuleModuleId',
  presentation: 'presentation',
  exercise: 'exercise',
  style: ':style',
  windowId: ':windowId',
  exerciseId: ':exerciseId',
  finalChallenge: 'finalChallenge',
};
